# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/arne/Documents/2022-2023/chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/arne/Documents/2022-2023/chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/arne/Documents/2022-2023/chess/CMakeFiles /mnt/c/Users/arne/Documents/2022-2023/chess//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/arne/Documents/2022-2023/chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess

# Build rule for target.
chess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess
.PHONY : chess

# fast build rule for target.
chess/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/build
.PHONY : chess/fast

src/AI.o: src/AI.cpp.o

.PHONY : src/AI.o

# target to build an object file
src/AI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/AI.cpp.o
.PHONY : src/AI.cpp.o

src/AI.i: src/AI.cpp.i

.PHONY : src/AI.i

# target to preprocess a source file
src/AI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/AI.cpp.i
.PHONY : src/AI.cpp.i

src/AI.s: src/AI.cpp.s

.PHONY : src/AI.s

# target to generate assembly for a file
src/AI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/AI.cpp.s
.PHONY : src/AI.cpp.s

src/BitboardHandler.o: src/BitboardHandler.cpp.o

.PHONY : src/BitboardHandler.o

# target to build an object file
src/BitboardHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/BitboardHandler.cpp.o
.PHONY : src/BitboardHandler.cpp.o

src/BitboardHandler.i: src/BitboardHandler.cpp.i

.PHONY : src/BitboardHandler.i

# target to preprocess a source file
src/BitboardHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/BitboardHandler.cpp.i
.PHONY : src/BitboardHandler.cpp.i

src/BitboardHandler.s: src/BitboardHandler.cpp.s

.PHONY : src/BitboardHandler.s

# target to generate assembly for a file
src/BitboardHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/BitboardHandler.cpp.s
.PHONY : src/BitboardHandler.cpp.s

src/Chess.o: src/Chess.cpp.o

.PHONY : src/Chess.o

# target to build an object file
src/Chess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Chess.cpp.o
.PHONY : src/Chess.cpp.o

src/Chess.i: src/Chess.cpp.i

.PHONY : src/Chess.i

# target to preprocess a source file
src/Chess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Chess.cpp.i
.PHONY : src/Chess.cpp.i

src/Chess.s: src/Chess.cpp.s

.PHONY : src/Chess.s

# target to generate assembly for a file
src/Chess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Chess.cpp.s
.PHONY : src/Chess.cpp.s

src/ChessStack.o: src/ChessStack.cpp.o

.PHONY : src/ChessStack.o

# target to build an object file
src/ChessStack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/ChessStack.cpp.o
.PHONY : src/ChessStack.cpp.o

src/ChessStack.i: src/ChessStack.cpp.i

.PHONY : src/ChessStack.i

# target to preprocess a source file
src/ChessStack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/ChessStack.cpp.i
.PHONY : src/ChessStack.cpp.i

src/ChessStack.s: src/ChessStack.cpp.s

.PHONY : src/ChessStack.s

# target to generate assembly for a file
src/ChessStack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/ChessStack.cpp.s
.PHONY : src/ChessStack.cpp.s

src/Interacter.o: src/Interacter.cpp.o

.PHONY : src/Interacter.o

# target to build an object file
src/Interacter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Interacter.cpp.o
.PHONY : src/Interacter.cpp.o

src/Interacter.i: src/Interacter.cpp.i

.PHONY : src/Interacter.i

# target to preprocess a source file
src/Interacter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Interacter.cpp.i
.PHONY : src/Interacter.cpp.i

src/Interacter.s: src/Interacter.cpp.s

.PHONY : src/Interacter.s

# target to generate assembly for a file
src/Interacter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Interacter.cpp.s
.PHONY : src/Interacter.cpp.s

src/Pieces/Bishop.o: src/Pieces/Bishop.cpp.o

.PHONY : src/Pieces/Bishop.o

# target to build an object file
src/Pieces/Bishop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Bishop.cpp.o
.PHONY : src/Pieces/Bishop.cpp.o

src/Pieces/Bishop.i: src/Pieces/Bishop.cpp.i

.PHONY : src/Pieces/Bishop.i

# target to preprocess a source file
src/Pieces/Bishop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Bishop.cpp.i
.PHONY : src/Pieces/Bishop.cpp.i

src/Pieces/Bishop.s: src/Pieces/Bishop.cpp.s

.PHONY : src/Pieces/Bishop.s

# target to generate assembly for a file
src/Pieces/Bishop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Bishop.cpp.s
.PHONY : src/Pieces/Bishop.cpp.s

src/Pieces/ChessPiece.o: src/Pieces/ChessPiece.cpp.o

.PHONY : src/Pieces/ChessPiece.o

# target to build an object file
src/Pieces/ChessPiece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/ChessPiece.cpp.o
.PHONY : src/Pieces/ChessPiece.cpp.o

src/Pieces/ChessPiece.i: src/Pieces/ChessPiece.cpp.i

.PHONY : src/Pieces/ChessPiece.i

# target to preprocess a source file
src/Pieces/ChessPiece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/ChessPiece.cpp.i
.PHONY : src/Pieces/ChessPiece.cpp.i

src/Pieces/ChessPiece.s: src/Pieces/ChessPiece.cpp.s

.PHONY : src/Pieces/ChessPiece.s

# target to generate assembly for a file
src/Pieces/ChessPiece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/ChessPiece.cpp.s
.PHONY : src/Pieces/ChessPiece.cpp.s

src/Pieces/King.o: src/Pieces/King.cpp.o

.PHONY : src/Pieces/King.o

# target to build an object file
src/Pieces/King.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/King.cpp.o
.PHONY : src/Pieces/King.cpp.o

src/Pieces/King.i: src/Pieces/King.cpp.i

.PHONY : src/Pieces/King.i

# target to preprocess a source file
src/Pieces/King.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/King.cpp.i
.PHONY : src/Pieces/King.cpp.i

src/Pieces/King.s: src/Pieces/King.cpp.s

.PHONY : src/Pieces/King.s

# target to generate assembly for a file
src/Pieces/King.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/King.cpp.s
.PHONY : src/Pieces/King.cpp.s

src/Pieces/Knight.o: src/Pieces/Knight.cpp.o

.PHONY : src/Pieces/Knight.o

# target to build an object file
src/Pieces/Knight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Knight.cpp.o
.PHONY : src/Pieces/Knight.cpp.o

src/Pieces/Knight.i: src/Pieces/Knight.cpp.i

.PHONY : src/Pieces/Knight.i

# target to preprocess a source file
src/Pieces/Knight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Knight.cpp.i
.PHONY : src/Pieces/Knight.cpp.i

src/Pieces/Knight.s: src/Pieces/Knight.cpp.s

.PHONY : src/Pieces/Knight.s

# target to generate assembly for a file
src/Pieces/Knight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Knight.cpp.s
.PHONY : src/Pieces/Knight.cpp.s

src/Pieces/Pawn.o: src/Pieces/Pawn.cpp.o

.PHONY : src/Pieces/Pawn.o

# target to build an object file
src/Pieces/Pawn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Pawn.cpp.o
.PHONY : src/Pieces/Pawn.cpp.o

src/Pieces/Pawn.i: src/Pieces/Pawn.cpp.i

.PHONY : src/Pieces/Pawn.i

# target to preprocess a source file
src/Pieces/Pawn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Pawn.cpp.i
.PHONY : src/Pieces/Pawn.cpp.i

src/Pieces/Pawn.s: src/Pieces/Pawn.cpp.s

.PHONY : src/Pieces/Pawn.s

# target to generate assembly for a file
src/Pieces/Pawn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Pawn.cpp.s
.PHONY : src/Pieces/Pawn.cpp.s

src/Pieces/Queen.o: src/Pieces/Queen.cpp.o

.PHONY : src/Pieces/Queen.o

# target to build an object file
src/Pieces/Queen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Queen.cpp.o
.PHONY : src/Pieces/Queen.cpp.o

src/Pieces/Queen.i: src/Pieces/Queen.cpp.i

.PHONY : src/Pieces/Queen.i

# target to preprocess a source file
src/Pieces/Queen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Queen.cpp.i
.PHONY : src/Pieces/Queen.cpp.i

src/Pieces/Queen.s: src/Pieces/Queen.cpp.s

.PHONY : src/Pieces/Queen.s

# target to generate assembly for a file
src/Pieces/Queen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Queen.cpp.s
.PHONY : src/Pieces/Queen.cpp.s

src/Pieces/Rook.o: src/Pieces/Rook.cpp.o

.PHONY : src/Pieces/Rook.o

# target to build an object file
src/Pieces/Rook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Rook.cpp.o
.PHONY : src/Pieces/Rook.cpp.o

src/Pieces/Rook.i: src/Pieces/Rook.cpp.i

.PHONY : src/Pieces/Rook.i

# target to preprocess a source file
src/Pieces/Rook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Rook.cpp.i
.PHONY : src/Pieces/Rook.cpp.i

src/Pieces/Rook.s: src/Pieces/Rook.cpp.s

.PHONY : src/Pieces/Rook.s

# target to generate assembly for a file
src/Pieces/Rook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/Rook.cpp.s
.PHONY : src/Pieces/Rook.cpp.s

src/Pieces/SlidingPiece.o: src/Pieces/SlidingPiece.cpp.o

.PHONY : src/Pieces/SlidingPiece.o

# target to build an object file
src/Pieces/SlidingPiece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/SlidingPiece.cpp.o
.PHONY : src/Pieces/SlidingPiece.cpp.o

src/Pieces/SlidingPiece.i: src/Pieces/SlidingPiece.cpp.i

.PHONY : src/Pieces/SlidingPiece.i

# target to preprocess a source file
src/Pieces/SlidingPiece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/SlidingPiece.cpp.i
.PHONY : src/Pieces/SlidingPiece.cpp.i

src/Pieces/SlidingPiece.s: src/Pieces/SlidingPiece.cpp.s

.PHONY : src/Pieces/SlidingPiece.s

# target to generate assembly for a file
src/Pieces/SlidingPiece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/Pieces/SlidingPiece.cpp.s
.PHONY : src/Pieces/SlidingPiece.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess.dir/build.make CMakeFiles/chess.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chess"
	@echo "... src/AI.o"
	@echo "... src/AI.i"
	@echo "... src/AI.s"
	@echo "... src/BitboardHandler.o"
	@echo "... src/BitboardHandler.i"
	@echo "... src/BitboardHandler.s"
	@echo "... src/Chess.o"
	@echo "... src/Chess.i"
	@echo "... src/Chess.s"
	@echo "... src/ChessStack.o"
	@echo "... src/ChessStack.i"
	@echo "... src/ChessStack.s"
	@echo "... src/Interacter.o"
	@echo "... src/Interacter.i"
	@echo "... src/Interacter.s"
	@echo "... src/Pieces/Bishop.o"
	@echo "... src/Pieces/Bishop.i"
	@echo "... src/Pieces/Bishop.s"
	@echo "... src/Pieces/ChessPiece.o"
	@echo "... src/Pieces/ChessPiece.i"
	@echo "... src/Pieces/ChessPiece.s"
	@echo "... src/Pieces/King.o"
	@echo "... src/Pieces/King.i"
	@echo "... src/Pieces/King.s"
	@echo "... src/Pieces/Knight.o"
	@echo "... src/Pieces/Knight.i"
	@echo "... src/Pieces/Knight.s"
	@echo "... src/Pieces/Pawn.o"
	@echo "... src/Pieces/Pawn.i"
	@echo "... src/Pieces/Pawn.s"
	@echo "... src/Pieces/Queen.o"
	@echo "... src/Pieces/Queen.i"
	@echo "... src/Pieces/Queen.s"
	@echo "... src/Pieces/Rook.o"
	@echo "... src/Pieces/Rook.i"
	@echo "... src/Pieces/Rook.s"
	@echo "... src/Pieces/SlidingPiece.o"
	@echo "... src/Pieces/SlidingPiece.i"
	@echo "... src/Pieces/SlidingPiece.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

